import os
import argparse


def get_args():
    parser = argparse.ArgumentParser()

    # Run Config
    parser.add_argument("--model_type", type=str, default='triangle', choices=['vast', 'triangle', 'triangle_cos'])
    parser.add_argument("--vision_resolution", default=224, type=int)
    parser.add_argument("--checkpoint", default=None, type=str)
    parser.add_argument("--output_dir", default='output/', type=str)
    parser.add_argument('--gradient_accumulation_steps', type=int, default=1)
    parser.add_argument("--learning_rate", default=None, type=float)
    parser.add_argument("--clip_lr", default=5e-7, type=float)
    parser.add_argument("--optim", type=str, default='adam', choices=['adam', 'adamax', 'adamw'])
    parser.add_argument("--betas", default=[0.9, 0.98], nargs='+')
    parser.add_argument("--weight_decay", default=0.01, type=float)
    parser.add_argument("--grad_norm", default=5.0, type=float)
    parser.add_argument("--warmup_ratio", default=0.1, type=float)
    parser.add_argument('--resume', type=str, default='yes', choices=['yes', 'no'], help='use txt out')
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument("--load_dtype", type=str, default='fp16', choices=['fp16', 'bf16'])
    parser.add_argument('--zero_shot', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--scheduler', type=str, default='warmup_linear')
    parser.add_argument("--save_best", type=str, default='yes', choices=['yes', 'no'])
    parser.add_argument("--log_steps", type=int, default=-1)
    parser.add_argument('--num_train_steps', type=int, default=0)
    parser.add_argument('--pretrain_dir', type=str, default="")
    parser.add_argument('--first_eval', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--remove_before_ckpt', type=str, default='yes', choices=['yes', 'no'])
    parser.add_argument('--dataset_mix_type', type=str, default='random')
    parser.add_argument('--valid_freq', type=int, default=10)
    parser.add_argument('--new_params_name', type=str, default=[], nargs='+')
    parser.add_argument('--new_lr', type=float, default=0.0)
    parser.add_argument('--mode', type=str, default='training', choices=['training', 'testing'])

    # Model Config
    parser.add_argument("--checkpointing", type=str, default='no', choices=['yes', 'no'])
    parser.add_argument("--frozen_vision", type=str, default='no', choices=['yes', 'no'])
    parser.add_argument("--ret_bidirection_evaluation", type=str, default='no', choices=['yes', 'no'])
    parser.add_argument("--itm_rerank_num", type=int, default=50)
    parser.add_argument("--itm_ratio", type=float, default=1.0)
    parser.add_argument('--vision_encoder_type', type=str, default='evaclip01_giant')
    parser.add_argument('--frame_embedding_type', type=str, default='')
    parser.add_argument('--multimodal_encoder_type', type=str, default='bert_base_uncased')
    parser.add_argument('--captioner_mode', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--beam_size', type=int, default=3)
    parser.add_argument('--generate_nums', type=int, default=1)
    parser.add_argument('--contra_dim', type=int, default=512)

    # Data Config
    parser.add_argument("--clip_lr_text", default=5e-7, type=float)
    parser.add_argument('--vision_transforms', type=str, default='none')

    # Other
    parser.add_argument("--local-rank", type=int, default=os.environ['LOCAL_RANK'])
    parser.add_argument("--dropout", default=0.1, type=float)
    parser.add_argument("--opt_model", default=None, type=str)
    parser.add_argument("--llm_model", default=None, type=str)
    parser.add_argument("--config")
    parser.add_argument("--max_generation_len", type=int, default=40)
    parser.add_argument("--max_length", type=int, default=30)
    parser.add_argument("--min_length", type=int, default=8)
    parser.add_argument("--max_output_txt_len", type=int, default=256)
    parser.add_argument("--amp", type=str, default='apex')
    parser.add_argument("--train_id", type=str, default='')
    parser.add_argument("--test_id", type=str, default='')
    parser.add_argument("--train_task", type=str, default='')
    parser.add_argument("--test_task", type=str, default='')
    parser.add_argument("--test_batch_size", type=int, default=-1)
    parser.add_argument("--max_text_tokens", type=int, default=40)
    parser.add_argument("--train_batch_size", type=int, default=-1)
    parser.add_argument("--scst_finetuning", type=str, default='no', choices=['yes', 'no'])
    parser.add_argument("--use_proposal_conv", type=str, default='yes', choices=['yes', 'no'])
    parser.add_argument('--trainer_type', type=str, default="")
    parser.add_argument("--train_epoch", type=float, default=-1)
    parser.add_argument("--contra_ratio", type=float, default=1.0)
    parser.add_argument("--train_steps", type=int, default=-1)
    parser.add_argument("--train_vision_sample_num", type=int, default=-1)
    parser.add_argument("--test_vision_sample_num", type=int, default=-1)
    parser.add_argument("--train_audio_sample_num", type=int, default=-1)
    parser.add_argument("--test_audio_sample_num", type=int, default=-1)
    parser.add_argument("--concatenated_nums", type=int, default=1)
    parser.add_argument('--loss_type', type=str, default='')
    parser.add_argument('--huggingface_trainer', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--deepspeed', type=str, default="")
    parser.add_argument('--prompt', type=str, default=None)
    parser.add_argument('--model_cfg_file', type=str, default="")
    parser.add_argument('--llm_type', type=str, default="")
    parser.add_argument('--dual_softmax', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--pool_video', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--use_flash_attn', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--qformer_question', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--frozen_llm', type=str, default='yes', choices=['yes', 'no'])
    parser.add_argument('--use_deepspeed', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--qformer_text_input', type=str, default='yes', choices=['yes', 'no'])
    parser.add_argument('--evaluate_ret_text', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--pool_vision', type=str, default='no', choices=['yes', 'no'])
    parser.add_argument('--vision_perceiver_query_num', type=int, default=-1)
    parser.add_argument('--beam_size_qa', type=int, default=1)
    parser.add_argument('--perceiver_mode', type=str, default='')
    parser.add_argument('--vision_cut_frames', type=int, default=-1)

    args = parser.parse_args()
    return args
